### ISSUE TITLE
Support for using private go modules

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/go-mod-vendor#140]
Requests for being able to use private repos as go modules has come up a couple times and probably something we should consider. Here's a recent question from @cirocosta around this:

> is it correct to say that the credentials used for the `prepare` step are not injected into the `build` step?
> the use case: i’ve got a private repo that depends on other private repos (via go modules) and I currently don’t vendor them all into the first - `build` currently seems unable to fetch those private dependencies

I'm filing this here as the specific request is around go modules, but likely that there's a solution for this across all buildpacks.

**Comment by cirocosta** [comment]
Hi!

Thanks for bringing it up, @kvedurmu !

@matthewmcnew had suggested using using service bindings for providing the credentials, so I came up with a little patch to this buildpack that allowed me to copy a `.netrc` injected via bindings to `$HOME/.netrc` where `git` could then read the creds to use in its transport (https)

```diff
diff --git a/build.go b/build.go
index 4736fbe..81f8977 100644
--- a/build.go
+++ b/build.go
@@ -1,6 +1,11 @@
 package gomodvendor

 import (
+       "fmt"
+       "io"
+       "os"
+       "path/filepath"
+
        "github.com/paketo-buildpacks/packit"
 )

@@ -10,10 +15,38 @@ type BuildProcess interface {
        Execute(path, workingDir string) error
 }

+func cp(src, dst string) error {
+       in, err := os.Open(src)
+       if err != nil {
+               return fmt.Errorf("open: %w", err)
+       }
+       defer in.Close()
+
+       out, err := os.Create(dst)
+       if err != nil {
+               return fmt.Errorf("create: %w", err)
+       }
+       defer out.Close()
+
+       if _, err = io.Copy(out, in); err != nil {
+               return fmt.Errorf("copy: %w", err)
+       }
+
+       return nil
+}
+
+const netrcFromBinding = "/platform/bindings/netrc/secret/.netrc"
+
 func Build(buildProcess BuildProcess, logs LogEmitter) packit.BuildFunc {
        return func(context packit.BuildContext) (packit.BuildResult, error) {
                logs.Title("%s %s", context.BuildpackInfo.Name, context.BuildpackInfo.Version)

+               if _, err := os.Stat(netrcFromBinding); !os.IsNotExist(err) {
+                       if err := cp(netrcFromBinding, filepath.Join(os.Getenv("HOME"), ".netrc")); err != nil {
+                               return packit.BuildResult{}, fmt.Errorf("cp: %w", err)
+                       }
+               }
+
                ok, err := buildProcess.ShouldRun(context.WorkingDir)
                if err != nil {
                        return packit.BuildResult{}, err
```

which then works great with `kpack`s use of service bindings:

```yaml
#@ load("@ytt:data", "data")

---
kind: Build
apiVersion: kpack.io/v1alpha1
metadata:
  name: build
spec:
  tags: ['harbor.internal.unicorns.com/my/thing']
  serviceAccount: controllers-creds
  bindings:
    - name: netrc
      metadataRef:
        name: netrc-metadata
      secretRef:
        name: bindings-netrc
  env:
    - name: NETRC
      value: "/platform/bindings/netrc/secret"
  builder:
    image: harbor.internal.unicorns.com/my/builder-with-patched-go-mod@sha256:12345
  source:
    git:
      url: 'https://gitlab.internal.unicorns.com/my/project'
      revision: a-revision
---
apiVersion: v1
kind: Secret
metadata:
  name: bindings-netrc
type: Opaque
stringData:
  .netrc: |-
    machine gitlab.internal.unicorns.com
    #@ "login" + data.values.git.username
    #@ "password" + data.values.git.token

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netrc-metadata
data:
  kind: go
  provider: sample
```

happy to help in any form!
